# Generated by Django 5.0.2 on 2024-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qname", models.CharField(max_length=30)),
                ("question1", models.CharField(max_length=5000)),
                ("answer1", models.CharField(max_length=5000)),
                ("question2", models.CharField(max_length=5000)),
                ("answer2", models.CharField(max_length=5000)),
                ("question3", models.CharField(max_length=5000)),
                ("answer3", models.CharField(max_length=5000)),
                ("question4", models.CharField(max_length=5000)),
                ("answer4", models.CharField(max_length=5000)),
                ("question5", models.CharField(max_length=5000)),
                ("answer5", models.CharField(max_length=5000)),
            ],
        ),
    ]
