# Generated by Django 5.0.2 on 2024-06-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=30)),
                ("uemail", models.EmailField(max_length=35, unique=True)),
                ("upass", models.CharField(max_length=20)),
                ("udob", models.DateField()),
                ("udesg", models.CharField(max_length=100)),
            ],
        ),
    ]
