# Generated by Django 5.0.2 on 2024-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="ucoins",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="register",
            name="urank",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="register",
            name="uscore",
            field=models.IntegerField(default=0),
        ),
    ]
